[package]
name = "pong_core"
version = "0.1.0"
authors = ["Tim Joseph <tim.joseph@mctigger.com>"]

[dependencies.stm32f7_discovery]
git = "https://github.com/embed-rs/stm32f7-discovery.git"
branch = "smoltcp"