[package]
name = "desktop"
version = "0.1.0"
authors = ["Tim Joseph <tim.joseph@mctigger.com>"]

[dependencies]
minifb = "0.10.4"
rand = "0.4.2"
itertools = "0.7.8"
pong_core = { path = "../pong_core" }